version: "3.7"

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d

  redis:
    image: redis:alpine3.12
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_AUTH}
    restart: always
    env_file: .env
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis/conf.d/redis.conf:/usr/local/etc/redis/redis.conf
