apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../bases
patchesStrategicMerge:
  - serviceaccount/external-secrets.yaml
  - clusterrole/external-secrets.yaml
  - clusterrolebinding/external-secrets.yaml
  - clusterrolebinding/external-secrets-auth.yaml
  - service/external-secrets.yaml
  - deployment/external-secrets.yaml
namespace: kube-system
images:
  - name: godaddy/kubernetes-external-secrets
    newTag: 6.0.0
