apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
  labels:
    app: todo
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo
          image: 048246832408.dkr.ecr.ap-northeast-1.amazonaws.com/todo-rest-service
          ports:
            - containerPort: 8082
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8082
          resources:
            requests:
              memory: 64Mi
              cpu: 250m
          envFrom:
            - configMapRef:
                name: todo-configmap
            - secretRef:
                name: todo-secret
