apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
  labels:
    app: account
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 3
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: 048246832408.dkr.ecr.ap-northeast-1.amazonaws.com/account-rest-service:${IMAGE_TAG}
          ports:
            - containerPort: 8081
          env:
            - name: ALLOWED_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: account-configmap
                  key: allowedOrigin
            - name: USER_HOST
              valueFrom:
                configMapKeyRef:
                  name: account-configmap
                  key: userHost
            - name: MYSQL_DSN
              valueFrom:
                secretKeyRef:
                  name: account-secret
                  key: mysqlDsn
            - name: REDIS_DSN
              valueFrom:
                secretKeyRef:
                  name: account-secret
                  key: redisDsn
            - name: REDIS_AUTH
              valueFrom:
                secretKeyRef:
                  name: account-secret
                  key: redisAuth
