apiVersion: v1
kind: Service
metadata:
  name: external-secrets
  labels:
    app.kubernetes.io/name: kubernetes-external-secrets
    helm.sh/chart: kubernetes-external-secrets-6.0.0
    app.kubernetes.io/instance: kakeibo
    app.kubernetes.io/managed-by: Helm
