apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 3
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: 048246832408.dkr.ecr.ap-northeast-1.amazonaws.com/user-rest-service:${IMAGE_TAG}
          ports:
            - containerPort: 8080
          env:
            - name: ALLOWED_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: user-configmap
                  key: allowedOrigin
            - name: ACCOUNT_HOST
              valueFrom:
                configMapKeyRef:
                  name: user-configmap
                  key: accountHost
