apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: account-hpa
  labels:
    app: account
spec:
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
