apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: account-secret
  labels:
    app: account
spec:
  backendType: secretsManager
  data:
    - key: account-db-dsn-secret
      name: MYSQL_DSN
      property: mysql_dsn
    - key: account-db-dsn-secret
      name: REDIS_DSN
      property: redis_dsn
