apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../bases
patchesStrategicMerge:
  - serviceaccount/aws-load-balancer-controller.yaml
  - deployment/aws-load-balancer-controller.yaml
