apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-secrets
  labels:
    app.kubernetes.io/name: kubernetes-external-secrets
    helm.sh/chart: kubernetes-external-secrets-6.0.0
    app.kubernetes.io/instance: kakeibo
    app.kubernetes.io/managed-by: Helm
spec:
  template:
    spec:
      containers:
        - name: kubernetes-external-secrets
          env:
            - name: "AWS_DEFAULT_REGION"
              value: "ap-northeast-1"
            - name: "AWS_REGION"
              value: "ap-northeast-1"
            - name: "LOG_LEVEL"
              value: "info"
            - name: "LOG_MESSAGE_KEY"
              value: "msg"
            - name: "METRICS_PORT"
              value: "3001"
            - name: "POLLER_INTERVAL_MILLISECONDS"
              value: "10000"
            - name: "VAULT_ADDR"
              value: "http://127.0.0.1:8200"
