apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: rds-secret
spec:
  backendType: secretsManager
  data:
    - key: rds-secret
      name: MYSQL_USER
      property: mysql_user
    - key: rds-secret
      name: MYSQL_PASSWORD
      property: mysql_password
    - key: rds-secret
      name: MYSQL_HOST
      property: mysql_host
    - key: rds-secret
      name: MYSQL_PORT
      property: mysql_port
