apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: user-secret
  labels:
    app: user
spec:
  backendType: secretsManager
  data:
    - key: user-db-dsn-secret
      name: MYSQL_DSN
      property: mysql_dsn
    - key: user-db-dsn-secret
      name: REDIS_DSN
      property: redis_dsn
