apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../bases
patchesStrategicMerge:
  - serviceaccount/alb-ingress-controller.yaml
  - deployment/alb-ingress-controller.yaml
