apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kubernetes-external-secrets
      app.kubernetes.io/instance: kakeibo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubernetes-external-secrets
        app.kubernetes.io/instance: kakeibo
    spec:
      serviceAccountName: external-secrets
      containers:
        - name: kubernetes-external-secrets
          image: godaddy/kubernetes-external-secrets
          ports:
            - name: prometheus
              containerPort: 3001
          imagePullPolicy: IfNotPresent
          resources:
            {}
          env:
            - name: "AWS_DEFAULT_REGION"
              value: "us-west-2"
            - name: "AWS_REGION"
              value: "ap-northeast-1"
            - name: "LOG_LEVEL"
              value: "info"
            - name: "LOG_MESSAGE_KEY"
              value: "msg"
            - name: "METRICS_PORT"
              value: "3001"
            - name: "POLLER_INTERVAL_MILLISECONDS"
              value: "10000"
            - name: "VAULT_ADDR"
              value: "http://127.0.0.1:8200"
      securityContext:
        runAsNonRoot: true
        fsGroup: 65534
