apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
  labels:
    app: todo
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 3
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo
          image: 048246832408.dkr.ecr.ap-northeast-1.amazonaws.com/todo-rest-service:${IMAGE_TAG}
          ports:
            - containerPort: 8082
          env:
            - name: ALLOWED_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: allowedOrigin
            - name: USER_HOST
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: userHost
