apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: todo-secret
spec:
  backendType: secretsManager
  data:
    - key: todo-db-dsn-secret
      name: MYSQL_DSN
      property: mysql_dsn
    - key: todo-db-dsn-secret
      name: REDIS_DSN
      property: redis_dsn
