name: account-rest-service build
on:
  push:
    branches:
      - master
    paths:
      - account-rest-service/**
      - .github/workflows/account-rest-service-build.yaml
defaults:
  run:
    shell: bash
jobs:
  build:
    name: account-rest-service build
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      ECR_REPOSITORY: account-rest-service
      IMAGE_TAG: release.${{ github.sha }}
      GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    steps:
      - name: Checkout paypay3/kakeibo-app-api code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Define ECR registry name
        run: echo "ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV

      - name: Build builder image
        run: |
          docker build \
          --target builder \
          --cache-from=$ECR_REGISTRY/$ECR_REPOSITORY:builder \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:builder \
          ./account-rest-service

      - name: Build image
        run: |
          docker build \
          --cache-from=$ECR_REGISTRY/$ECR_REPOSITORY:builder \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:latest \
          ./account-rest-service

      - name: Push image to Amazon ECR
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:builder &
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG &
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest &
          wait

      - name: Checkout paypay3/kakeibo-app-kubernetes code
        uses: actions/checkout@v2
        with:
          repository: paypay3/kakeibo-app-kubernetes

      - name: Kustomize edit set image tag
        run: |
          kustomize edit set image 048246832408.dkr.ecr.ap-northeast-1.amazonaws.com/account-rest-service:$IMAGE_TAG
        working-directory: api/account-rest-service/overlays/production

      - name: Commit and push and create pull request
        run: |
          RELEASE_BRANCH=$(uuidgen)

          git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all
          git config --global user.name $GITHUB_USER
          git config --global user.email $GITHUB_EMAIL
          git remote set-url origin https://paypay3:$GITHUB_PASSWORD@github.com/paypay3/kakeibo-app-kubernetes.git
          git checkout -b $RELEASE_BRANCH

          git add -A
          git commit -m "Update docker image tag for account-rest-service to $IMAGE_TAG"
          git push origin $RELEASE_BRANCH

          COMMIT_HASH=$(git rev-parse --short HEAD)
          PR_COMMENT="$COMMIT_HASH<br>Update docker image tag for account-rest-service to \`$IMAGE_TAG\`"

          gh pr create \
          --base main \
          --head $RELEASE_BRANCH \
          --assignee $ASSIGNEES \
          --title "Update docker image tag for api" \
          --body "$PR_COMMENT" || \
          gh pr review \
          --comment \
          --body "$PR_COMMENT"
        env:
          GITHUB_USER: "Yusuke Taira"
          GITHUB_EMAIL: "ney07214545@icloud.com"
          GITHUB_PASSWORD: ${{ secrets.ACCESS_PASSWORD }}
          ASSIGNEES: ${{ github.actor }}
