name: user-rest-service
on: [pull_request]
defaults:
  run:
    shell: bash
    working-directory: user-rest-service
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.30
          args: --timeout=3m0s
      - name: Run tests
        run: go test -race -v ./...
