name: user-rest-service build
on:
  push:
    branches:
      - master
    paths:
      - user-rest-service/**
      - .github/workflows/user-rest-service-build.yaml
defaults:
  run:
    shell: bash
    working-directory: user-rest-service
jobs:
  build:
    name: user-rest-service build
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      ECR_REPOSITORY: user-rest-service
      IMAGE_TAG: release.${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Define ECR registry name
        run: echo ::set-env name=ECR_REGISTRY::${{ steps.login-ecr.outputs.registry }}

      - name: Build builder image
        run: |
          docker build \
          --target builder \
          --cache-from=$ECR_REGISTRY/$ECR_REPOSITORY:builder \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:builder .

      - name: Build image
        run: |
          docker build \
          --cache-from=$ECR_REGISTRY/$ECR_REPOSITORY:builder \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .

      - name: Push image to Amazon ECR
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:builder &
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG &
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest &
          wait
